### ISSUE TITLE
[new feature] docker support for selfhosting?

### ISSUE THREAD

**Issue by ferivoq** [detarkende/stremio-ncore-addon#1]
Hey! Could you add a dockerfile for it so you can selfhost using docker?

**Comment by hauserkristof** [comment]
```
# Build stage
FROM node:20.11.1-bookworm AS builder
WORKDIR /app
COPY package*.json ./
COPY ./patches ./patches
RUN npm install
COPY . .
RUN npm run build
RUN apt-get update && apt-get install -y \
    build-essential \
    python3
COPY config.json ./config.json

EXPOSE 3000
CMD ["npm", "run", "start"]
```

**Comment by hauserkristof** [comment]
See the #2 PR @ferivoq

**Comment by ferivoq** [comment]
Cool as I can see it should work. But if I've made it I would completly change the whole thing to work with env variables instead of json.

**Comment by hauserkristof** [comment]
That would be great, yes, I just made this for a quick and dirty solution.

**Comment by detarkende** [comment]
@hauserkristof I'm currently working on a rework of major parts of the app, so the dockerfile might have to change a bit, but I'm copying your changes over to that branch (not public yet).

@ferivoq I agree, it would be better to provide most of the config in environment variables. The only reason for having a config.js file is that I want the addon to have multiple users and I don't see any viable ways of providing an array of users in an env var. Any ideas on that?

**Comment by hauserkristof** [comment]
We could also keep the `config.json` with a feature flag maybe like `USE_CONFIG_FILE`

**Comment by detarkende** [comment]
@hauserkristof I'm likely moving everything to astro (which has built in env var validation, coincidentally it also uses zod).

I guess you can write arrays in env vars, but if you look at the example config json's users array, you'll see that it's an array of quite nested objects. It wouldn't be easy to use.

Since we already have to mount two volumes (for torrents and for downloads), what if we mounted another volume for an optional users.json?

```bash
docker run stremio-ncore-addon \
  -v users.json:users.json \
  -v /media/share/torrents:/torrents \
  -v /media/share/downloads:/downloads \
  -e PORT=3000 \
  -e ADMIN_USERNAME=example \
  -e ADMIN_PASSWORD=example \
  -e TORRENT_DIR=/torrents \
  -e DOWNLOADS_DIR=/downloads \
  -p 3000:3000
# ...
```
Note: the env vars TORRENT_DIR and DOWNLOADS_DIR would be completely optional, but you should still be able to run the app without docker, so we can't just hardcode `/torrents` and `/downloads`.

**Comment by hauserkristof** [comment]
I think thats fair! The most critical part would be the nCore username, password and the secret, that should be an env var.

Astro sounds cool!

**Comment by detarkende** [comment]
@hauserkristof @ferivoq  - I prepared a PR for this. 

The config file has been replaced by environment variables in a previous PR, so I was able to dockerize the app easily.

Feel free to leave comments on the PR, I won't merge it until I have at leas one of your approvals.
